AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'lib/anycable/rpc/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4

Rails:
  Enabled: false

# Naming/AccessorMethodName:
#   Enabled: false

# Naming/UncommunicativeMethodParamName:
#   Enabled: false

# Style/PercentLiteralDelimiters:
#   Enabled: false

# Style/TrivialAccessors:
#   Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals: 
  EnforcedStyle: double_quotes

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/HandleExceptions:
  Enabled: false
