---
- name: Benchmark Client
  hosts: benchmark
  sudo: yes
  remote_user: ubuntu
  gather_facts: False
  vars:
    server_host: '172.31.22.14'
    hostname: ws-bench-client
    local_ips: ['172.31.21.241', '172.31.21.242', '172.31.21.243', '172.31.21.244']
    local_ips_str: '-l 172.31.21.241 -l 172.31.21.242 -l 172.31.21.243 -l 172.31.21.244'
    steps: 10
    step_size: 1000
    sample_size: 40
    prepare: False
  tasks:
    - name: Prepare the machine
      when: prepare
      block:
        - hostname:
            name: "{{ hostname }}"
        - lineinfile:
            path: /etc/hosts
            line: '127.0.0.1 {{ hostname }}'
            state: present
        - shell: ip addr add {{ item }}/20 dev eth0
          with_items: "{{ local_ips }}"
    - name: Action Cable benchmark
      become_user: deplo
      shell: bin/websocket-bench broadcast {{ local_ips_str }} --concurrent 4 --sample-size {{ sample_size }} --step-size {{ step_size }} --payload-padding 200 --total-steps {{ steps }} --origin http://0.0.0.0 ws://{{ server_host }}:3334/cable --server-type=actioncable
      register: bench
      tags: action_cable
      args:
        chdir: /webapps/anycable_bench
      ignore_errors: yes

    - name: Benchmark results
      debug: var=bench.stdout_lines
      tags:
        - action_cable
